language: python
python:
- 3.6
install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt
script:
- pytest --cov phone_numbers
- flake8
after_success:
- coveralls
- pip install -r requirements.txt
- pip install zappa
- zappa update production
